var JSLIFE=JSLIFE||{};
(function(){JSLIFE.configuration={};JSLIFE.configuration.Configuration=function(){this.targetDivId="canvas";this.horizontalBlocks=50;this.height=this.width=150;this.foregroundColor="blue";this.backgroundColor="black";this.backgroundStrokeColor=this.foregroundStrokeColor="white";this.updateSpeed=50;this.getTargetDivId=function(){return this.targetDivId};this.getHorizontalBlocks=function(){return this.horizontalBlocks};this.getForegroundColor=function(){return this.foregroundColor};this.getBackgroundColor=
function(){return this.backgroundColor};this.getForegroundStrokeColor=function(){return this.foregroundStrokeColor};this.getBackgroundStrokeColor=function(){return this.backgroundStrokeColor};this.getUpdateSpeed=function(){return this.updateSpeed};this.getWidth=function(){return this.width};this.getHeight=function(){return this.height};this.withTargetDivId=function(b){this.targetDivId=b;return this};this.withHorizontalBlocks=function(b){this.horizontalBlocks=b;return this};this.withForegroundColor=
function(b){this.foregroundColor=b;return this};this.withBackgroundColor=function(b){this.backgroundColor=b;return this};this.withForegroundStrokeColor=function(b){this.foregroundStrokeColor=b;return this};this.withBackgroundStrokeColor=function(b){this.backgroundStrokeColor=b;return this};this.withUpdateSpeed=function(b){this.updateSpeed=b;return this};this.withWidth=function(b){this.width=b;return this};this.withHeight=function(b){this.height=b;return this}}})();JSLIFE=JSLIFE||{};void 0==this.Raphael&&alert("Oops, the Raphaeljs framework was not found...");if(!Array.prototype.filter)Array.prototype.filter=function(b,h){var d=this.length>>>0;if("function"!=typeof b)throw new TypeError;for(var c=[],a=0;a<d;a++)if(a in this){var i=this[a];b.call(h,i,a,this)&&c.push(i)}return c};
(function(){JSLIFE.core={};var b=new JSLIFE.configuration.Configuration;JSLIFE.core.JSLife=function(h){this.init=function(d){var c=this.makeRaphaelPaper(d),a=this.makeEmptyState(c,d);this.randomize(a);this.loop(c,a,d)};this.makeRaphaelPaper=function(d){return Raphael(d.targetDivId,"100%","100%")};this.makeEmptyState=function(d,c){var a={},b=c.horizontalBlocks+2,e,j=c.width/c.horizontalBlocks,h=Math.floor(c.height/j)+2,f,g=this;a.each=function(c,d){var k=!d?1:0;for(f=k;f<h-k;f++)for(e=k;e<b-k;e++){var j=
a[g.makeKey(e,f)];c(j,e,f)}};a.resetChangelings=function(){this.changelings={}};a.eachChangeling=function(a){for(var c in this.changelings)if(this.changelings.hasOwnProperty(c)){var d=this.changelings[c];d.dummy||a(d)}};a.live=function(a){this.setTaken(a,!0)};a.die=function(a){this.setTaken(a,!1)};a.setTaken=function(a,c){a.taken=c;this.changelings[a.key]=a;var d=a.neighbours.length,b;for(b=0;b<d;b++){var e=a.neighbours[b];e.dummy||(this.changelings[e.key]=e)}};a.resetChangelings();for(f=0;f<h;f++)for(e=
0;e<b;e++){var l;l=0<e&&e<b-1&&0<f&&f<h-1?this.makeRealRect(d,e,f,j):this.makeDummyRect(e,f);a[l.key]=l}a.each(function(c,d,b){c.neighbours=[a[g.makeKey(d,b-1)],a[g.makeKey(d,b+1)],a[g.makeKey(d-1,b)],a[g.makeKey(d+1,b)],a[g.makeKey(d-1,b-1)],a[g.makeKey(d+1,b-1)],a[g.makeKey(d-1,b+1)],a[g.makeKey(d+1,b+1)]];c.takenNeighbours=function(){return this.neighbours.filter(function(a){return a.taken})}});return a};this.makeKey=function(d,c){return d+"_"+c};this.randomize=function(d){d.each(function(c){var a=
5<Math.floor(11*Math.random())?!0:!1;d.setTaken(c,a)})};this.makeRealRect=function(d,c,a,b){d=d.rect((c-1)*b,(a-1)*b,b,b);d.key=this.makeKey(c,a);return d};this.makeDummyRect=function(b,c){var a={taken:!1};a.key=this.makeKey(b,c);a.attr=function(){};a.dummy=!0;return a};this.loop=function(b,c,a){this.evolve(c,a);this.render(b,c,a);var i=this;setTimeout(function(){i.loop(b,c,a)},a.updateSpeed)};this.evolve=function(b){var c=[];b.eachChangeling(function(a){var b=a.takenNeighbours().length;2>b&&a.taken?
c.push({alive:!1,rect:a}):3<b&&a.taken?c.push({alive:!1,rect:a}):(2===b||3===b)&&a.taken?c.push({alive:!0,rect:a}):!a.taken&&3===b&&c.push({alive:!0,rect:a})});b.resetChangelings();for(var a=c.length-1;0<=a;){var i=c[a];b.setTaken(i.rect,i.alive);a-=1}};this.render=function(b,c,a){c.each(function(b){!0==b.taken?(b.attr("fill",a.foregroundColor),b.attr("stroke",a.foregroundStrokeColor)):(b.attr("fill",a.backgroundColor),b.attr("stroke",a.backgroundStrokeColor))})};this.init(h||b)}})();
