var JSLIFE=JSLIFE||{};
(function(){JSLIFE.configuration={};JSLIFE.configuration.Configuration=function(){this.targetDivId="canvas";this.horizontalBlocks=50;this.foregroundColor="blue";this.backgroundColor="black";this.backgroundStrokeColor=this.foregroundStrokeColor="white";this.strokeWidth=1;this.updateSpeed=100;this.withTargetDivId=function(e){this.targetDivId=e;return this};this.withHorizontalBlocks=function(e){this.horizontalBlocks=e;return this};this.withForegroundColor=function(e){this.foregroundColor=e;return this};
this.withBackgroundColor=function(e){this.backgroundColor=e;return this};this.withForegroundStrokeColor=function(e){this.foregroundStrokeColor=e;return this};this.withBackgroundStrokeColor=function(e){this.backgroundStrokeColor=e;return this};this.withUpdateSpeed=function(e){this.updateSpeed=e;return this};this.withStrokeWidth=function(e){this.strokeWidth=e;return this};this.withInitialState=function(e){this.initialState=e;return this}}})();JSLIFE=JSLIFE||{};if(!Array.prototype.filter)Array.prototype.filter=function(e,k){var c=this.length>>>0;if("function"!=typeof e)throw new TypeError;for(var b=[],a=0;a<c;a++)if(a in this){var d=this[a];e.call(k,d,a,this)&&b.push(d)}return b};
(function(){JSLIFE.core={};var e=new JSLIFE.configuration.Configuration;JSLIFE.core.JSLife=function(k){this.init=function(c){var b=this.makeCanvasContext(c),a=this.makeEmptyState(b,c);this.enableInteraction(b,a);void 0==c.initialState?this.randomize(a):this.applyState(c.initialState,a);this.loop(b,a,c)};this.applyState=function(c,b){var a=this;b.each(function(d){var f=-1==c.indexOf(a.makeKey(d.x-1,d.y-1))?!1:!0;b.setTaken(d,f)})};this.enableInteraction=function(c,b){var a=this;c.canvas.addEventListener("mousemove",
function(d){var f;d.pageX||d.pageY?(f=d.pageX,d=d.pageY):(f=d.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d=d.clientY+document.body.scrollTop+document.documentElement.scrollTop);var d=d-c.canvas.offsetTop,e=a.makeKey(0,0);b.live(b[a.makeKey(Math.floor(f/b[e].side),Math.floor(d/b[e].side))])},!1)};this.makeCanvasContext=function(c){return document.getElementById(c.targetDivId).getContext("2d")};this.makeEmptyState=function(c,b){var a={},d=b.horizontalBlocks+2,f,e=Math.floor((c.canvas.clientWidth-
d*b.strokeWidth)/(d-2)),j=Math.floor(c.canvas.clientHeight/e+2),g,i=this;a.each=function(c,b){var e=!b?1:0;for(g=e;g<j-e;g++)for(f=e;f<d-e;f++){var h=a[i.makeKey(f,g)];c(h,f,g)}};a.resetChangelings=function(){this.changelings={}};a.eachChangeling=function(a){for(var c in this.changelings)if(this.changelings.hasOwnProperty(c)){var b=this.changelings[c];b.dummy||a(b)}};a.live=function(a){this.setTaken(a,!0)};a.die=function(a){this.setTaken(a,!1)};a.setTaken=function(a,c){a.taken=c;this.changelings[a.key]=
a;var b=a.neighbours.length,d;for(d=0;d<b;d++){var e=a.neighbours[d];e.dummy||(this.changelings[e.key]=e)}};a.resetChangelings();for(g=0;g<j;g++)for(f=0;f<d;f++){var k=this.makeRect(c,f,g,e,!(0<f&&f<d-1&&0<g&&g<j-1));a[k.key]=k}a.each(function(c,b,d){c.neighbours.push(a[i.makeKey(b-1,d)]);c.neighbours.push(a[i.makeKey(b+1,d)]);c.neighbours.push(a[i.makeKey(b,d+1)]);c.neighbours.push(a[i.makeKey(b,d-1)]);c.neighbours.push(a[i.makeKey(b-1,d-1)]);c.neighbours.push(a[i.makeKey(b-1,d+1)]);c.neighbours.push(a[i.makeKey(b+
1,d-1)]);c.neighbours.push(a[i.makeKey(b+1,d+1)])});return a};this.makeKey=function(c,b){return c+"_"+b};this.randomize=function(c){c.each(function(b){var a=5<Math.floor(11*Math.random())?!0:!1;c.setTaken(b,a)})};this.makeRect=function(c,b,a,d,e){return{taken:!1,x:b,y:a,key:this.makeKey(b,a),side:d,dummy:e,neighbours:[],takenNeighbours:function(){return this.neighbours.filter(function(a){return a.taken})}}};this.loop=function(c,b,a){this.render(c,b,a);this.evolve(b,a);var d=this;setTimeout(function(){d.loop(c,
b,a)},a.updateSpeed)};this.evolve=function(c){var b=[];c.eachChangeling(function(a){var c=a.takenNeighbours().length;2>c&&a.taken?b.push({alive:!1,rect:a}):3<c&&a.taken?b.push({alive:!1,rect:a}):(2===c||3===c)&&a.taken?b.push({alive:!0,rect:a}):!a.taken&&3===c&&b.push({alive:!0,rect:a})});c.resetChangelings();for(var a=b.length-1;0<=a;){var d=b[a];c.setTaken(d.rect,d.alive);a-=1}};this.render=function(c,b,a){b.each(function(b){var e,h=b.side,j=b.x-1,g=b.y-1;!0==b.taken?(b="function"==typeof a.foregroundColor?
a.foregroundColor(j,g):a.foregroundColor,e=a.foregroundStrokeColor):(b=a.backgroundColor,e=a.backgroundStrokeColor);c.fillStyle=b;c.strokeStyle=e;c.lineWidth=a.strokeWidth;c.fillRect(j*h,g*h,h,h);c.strokeRect(j*h,g*h,h,h)})};this.init(k||e)}})();
