var JSLIFE=JSLIFE||{};
(function(){JSLIFE.configuration={};JSLIFE.configuration.Configuration=function(){this.targetDivId="canvas";this.horizontalBlocks=50;this.foregroundColor="blue";this.backgroundColor="black";this.backgroundStrokeColor=this.foregroundStrokeColor="white";this.strokeWidth=1;this.updateSpeed=100;this.withTargetDivId=function(e){this.targetDivId=e;return this};this.withHorizontalBlocks=function(e){this.horizontalBlocks=e;return this};this.withForegroundColor=function(e){this.foregroundColor=e;return this};
this.withBackgroundColor=function(e){this.backgroundColor=e;return this};this.withForegroundStrokeColor=function(e){this.foregroundStrokeColor=e;return this};this.withBackgroundStrokeColor=function(e){this.backgroundStrokeColor=e;return this};this.withUpdateSpeed=function(e){this.updateSpeed=e;return this};this.withStrokeWidth=function(e){this.strokeWidth=e;return this};this.withInitialState=function(e){this.initialState=e;return this}}})();JSLIFE=JSLIFE||{};if(!Array.prototype.filter)Array.prototype.filter=function(e,k){var b=this.length>>>0;if("function"!=typeof e)throw new TypeError;for(var c=[],a=0;a<b;a++)if(a in this){var d=this[a];e.call(k,d,a,this)&&c.push(d)}return c};
(function(){JSLIFE.core={};var e=new JSLIFE.configuration.Configuration;JSLIFE.core.JSLife=function(k){this.init=function(b){var c=this.makeCanvasContext(b),a=this.makeEmptyState(c,b);this.enableInteraction(c,a);void 0==b.initialState?this.randomize(a):this.applyState(b.initialState,a);this.loop(c,a,b)};this.applyState=function(b,c){var a=this;c.each(function(d){var f=-1==b.indexOf(a.makeKey(d.x-1,d.y-1))?!1:!0;c.setTaken(d,f)})};this.enableInteraction=function(b,c){var a=this;b.canvas.addEventListener("mousemove",
function(d){var f;d.pageX||d.pageY?(f=d.pageX,d=d.pageY):(f=d.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d=d.clientY+document.body.scrollTop+document.documentElement.scrollTop);f-=b.canvas.offsetLeft;console.log(b.canvas.offsetTop);var d=d-b.canvas.offsetTop,e=a.makeKey(0,0);c.live(c[a.makeKey(Math.floor(f/c[e].side),Math.floor(d/c[e].side))])},!1)};this.makeCanvasContext=function(b){return document.getElementById(b.targetDivId).getContext("2d")};this.makeEmptyState=function(b,
c){var a={},d=c.horizontalBlocks+2,f,e=Math.floor((b.canvas.clientWidth-d*c.strokeWidth)/(d-2)),j=Math.floor(b.canvas.clientHeight/e+2),g,i=this;a.each=function(b,c){var e=!c?1:0;for(g=e;g<j-e;g++)for(f=e;f<d-e;f++){var h=a[i.makeKey(f,g)];b(h,f,g)}};a.resetChangelings=function(){this.changelings={}};a.eachChangeling=function(a){for(var b in this.changelings)if(this.changelings.hasOwnProperty(b)){var c=this.changelings[b];c.dummy||a(c)}};a.live=function(a){this.setTaken(a,!0)};a.die=function(a){this.setTaken(a,
!1)};a.setTaken=function(a,b){a.taken=b;this.changelings[a.key]=a;var c=a.neighbours.length,d;for(d=0;d<c;d++){var f=a.neighbours[d];f.dummy||(this.changelings[f.key]=f)}};a.resetChangelings();for(g=0;g<j;g++)for(f=0;f<d;f++){var k=this.makeRect(b,f,g,e,!(0<f&&f<d-1&&0<g&&g<j-1));a[k.key]=k}a.each(function(b,c,d){b.neighbours.push(a[i.makeKey(c-1,d)]);b.neighbours.push(a[i.makeKey(c+1,d)]);b.neighbours.push(a[i.makeKey(c,d+1)]);b.neighbours.push(a[i.makeKey(c,d-1)]);b.neighbours.push(a[i.makeKey(c-
1,d-1)]);b.neighbours.push(a[i.makeKey(c-1,d+1)]);b.neighbours.push(a[i.makeKey(c+1,d-1)]);b.neighbours.push(a[i.makeKey(c+1,d+1)])});return a};this.makeKey=function(b,c){return b+"_"+c};this.randomize=function(b){b.each(function(c){var a=5<Math.floor(11*Math.random())?!0:!1;b.setTaken(c,a)})};this.makeRect=function(b,c,a,d,f){return{taken:!1,x:c,y:a,key:this.makeKey(c,a),side:d,dummy:f,neighbours:[],takenNeighbours:function(){return this.neighbours.filter(function(a){return a.taken})}}};this.loop=
function(b,c,a){this.render(b,c,a);this.evolve(c,a);var d=this;setTimeout(function(){d.loop(b,c,a)},a.updateSpeed)};this.evolve=function(b){var c=[];b.eachChangeling(function(a){var b=a.takenNeighbours().length;2>b&&a.taken?c.push({alive:!1,rect:a}):3<b&&a.taken?c.push({alive:!1,rect:a}):(2===b||3===b)&&a.taken?c.push({alive:!0,rect:a}):!a.taken&&3===b&&c.push({alive:!0,rect:a})});b.resetChangelings();for(var a=c.length-1;0<=a;){var d=c[a];b.setTaken(d.rect,d.alive);a-=1}};this.render=function(b,
c,a){c.each(function(c){var e,h=c.side,j=c.x-1,g=c.y-1;!0==c.taken?(c="function"==typeof a.foregroundColor?a.foregroundColor(j,g):a.foregroundColor,e=a.foregroundStrokeColor):(c=a.backgroundColor,e=a.backgroundStrokeColor);b.fillStyle=c;b.strokeStyle=e;b.lineWidth=a.strokeWidth;b.fillRect(j*h,g*h,h,h);b.strokeRect(j*h,g*h,h,h)})};this.init(k||e)}})();
